/**
 * data.ts – Static JSON data layer (Vercel-compatible)
 *
 * - stories.json  → imported statically (small, ~metadata only)
 * - chapters/*.json → read via fs.readFileSync at request time
 *   (files are included in the Vercel bundle via outputFileTracingIncludes)
 *
 * Generated by:  node scripts/build-data.mjs   (runs automatically as prebuild)
 */

import fs from "fs";
import path from "path";
import storiesJson from "@/data/stories.json";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface StoryMeta {
  url: string;
  title: string;
  author: string;
  genres: string[];
  categories: string[];
  status: string;
  num_chapters: number;
  slug: string;
}

export interface ChapterInfo {
  number: number;
  title: string;
  fileName: string;
}

// ── Story helpers ─────────────────────────────────────────────────────────────

const _stories: StoryMeta[] = storiesJson as StoryMeta[];

export function getAllStories(): StoryMeta[] {
  return _stories;
}

export function getStoryBySlug(slug: string): StoryMeta | null {
  return _stories.find((s) => s.slug === slug) ?? null;
}

// ── Chapter helpers ───────────────────────────────────────────────────────────

// In Next.js on Vercel, process.cwd() is the project root (web/)
const CHAPTERS_DIR = path.join(process.cwd(), "src", "data", "chapters");

interface ChapterFileData {
  chapters: ChapterInfo[];
  content: Record<string, { title: string; content: string }>;
}

function loadChapterFile(slug: string): ChapterFileData | null {
  const filePath = path.join(CHAPTERS_DIR, `${slug}.json`);
  try {
    const raw = fs.readFileSync(filePath, "utf-8");
    return JSON.parse(raw) as ChapterFileData;
  } catch {
    return null;
  }
}

export function getChapterList(slug: string): ChapterInfo[] {
  const data = loadChapterFile(slug);
  return data?.chapters ?? [];
}

export function getChapterContent(
  slug: string,
  chapterNum: number
): { title: string; content: string } | null {
  const data = loadChapterFile(slug);
  if (!data) return null;
  return data.content[String(chapterNum)] ?? null;
}

// ── Filter helpers ────────────────────────────────────────────────────────────

export function getAllGenres(): string[] {
  const set = new Set<string>();
  for (const s of _stories) for (const g of s.genres) set.add(g);
  return Array.from(set).sort((a, b) => a.localeCompare(b, "vi"));
}

export function getAllCategories(): { name: string; count: number }[] {
  const map = new Map<string, number>();
  for (const s of _stories) {
    for (const c of s.categories) map.set(c, (map.get(c) ?? 0) + 1);
  }
  return Array.from(map.entries())
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count);
}

export function getGenresWithCount(): { name: string; count: number }[] {
  const map = new Map<string, number>();
  for (const s of _stories) {
    for (const g of s.genres) map.set(g, (map.get(g) ?? 0) + 1);
  }
  return Array.from(map.entries())
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count);
}

export function getAllAuthors(): string[] {
  const set = new Set<string>();
  for (const s of _stories) if (s.author) set.add(s.author);
  return Array.from(set).sort((a, b) => a.localeCompare(b, "vi"));
}

export function getAuthorsWithCount(): { name: string; count: number }[] {
  const map = new Map<string, number>();
  for (const s of _stories) {
    if (s.author) map.set(s.author, (map.get(s.author) ?? 0) + 1);
  }
  return Array.from(map.entries())
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count);
}
